server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.49.191:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: toby
  jpa:
    database: mysql
    show-sql: true