server:
  port: 9005
spring:
  application:
    name: tensquart-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.49.191:3306/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: toby
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
