server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.49.191:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: toby
  redis:
    host: 39.98.49.191
  rabbitmq:
    host: 39.98.49.191


